### ISSUE TITLE
Social login doesnt work

### ISSUE THREAD

**Issue by jabas06** [backand/backand-ionic-social#1]
I cant make the social login work. I created a new facebook app, that automatically is created with for facebook api 2.5, to test this starter but a I get this error "Facebook account authenticated but did not return an email"

I configured all stuff required (app secret, redirect url, etc)

So, I tested the starter with other two facebook apps that a created before for other projects using firebase. I kept the code generated by the starter untouched, and the same Backand App. I just changed the App secret and API ID and I added the redirect URL to the facebook apps.

This are the results:

App 1: Backand login works well. The facebook api is 2.3

App 2: Backand login fails with error "Facebook account authenticated but did not return an email". The facebook api is 2.5. This app works well with firebase social login.

I'm not sure if the API version is the problem.

Could you validate this starter with a freshly created facebook app?

**Comment by Shpionus** [comment]
I have similar problem. In my case error happens only if login in facebook by owner of facebook app. For other users it works.

**Comment by itayher** [comment]
Issue fixed for FB latest api
